// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type GenerateReportRequest struct {
	StartDate string `json:"start_date"`
	EndDate   string `json:"end_date"`
}

type GenerateReportResponse struct {
	FileName string `json:"file_name"`
}
