// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	account "github.com/Drengin6306/ZeroBank/service/account/api/internal/handler/account"
	"github.com/Drengin6306/ZeroBank/service/account/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 企业用户注册
				Method:  http.MethodPost,
				Path:    "/enterprise/register",
				Handler: account.EnterpriseRegisterHandler(serverCtx),
			},
			{
				// 用户登录
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: account.LoginHandler(serverCtx),
			},
			{
				// 个人用户注册
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: account.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取用户余额
				Method:  http.MethodGet,
				Path:    "/balance",
				Handler: account.GetBalanceHandler(serverCtx),
			},
			{
				// 存款
				Method:  http.MethodPost,
				Path:    "/deposit",
				Handler: account.DepositHandler(serverCtx),
			},
			{
				// 获取用户信息
				Method:  http.MethodGet,
				Path:    "/userinfo",
				Handler: account.GetUserInfoHandler(serverCtx),
			},
			{
				// 取款
				Method:  http.MethodPost,
				Path:    "/withdraw",
				Handler: account.WithdrawHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)
}
