// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	transactionRecordFieldNames          = builder.RawFieldNames(&TransactionRecord{})
	transactionRecordRows                = strings.Join(transactionRecordFieldNames, ",")
	transactionRecordRowsExpectAutoSet   = strings.Join(stringx.Remove(transactionRecordFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	transactionRecordRowsWithPlaceHolder = strings.Join(stringx.Remove(transactionRecordFieldNames, "`transaction_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	transactionRecordModel interface {
		Insert(ctx context.Context, data *TransactionRecord) (sql.Result, error)
		FindOne(ctx context.Context, transactionId string) (*TransactionRecord, error)
		Update(ctx context.Context, data *TransactionRecord) error
		Delete(ctx context.Context, transactionId string) error
	}

	defaultTransactionRecordModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TransactionRecord struct {
		TransactionId   string         `db:"transaction_id"`
		AccountFrom     string         `db:"account_from"`
		AccountTo       sql.NullString `db:"account_to"`
		TransactionType int64          `db:"transaction_type"`
		Amount          float64        `db:"amount"`
		CreatedAt       time.Time      `db:"created_at"`
		Status          int64          `db:"status"`
	}
)

func newTransactionRecordModel(conn sqlx.SqlConn) *defaultTransactionRecordModel {
	return &defaultTransactionRecordModel{
		conn:  conn,
		table: "`transaction_record`",
	}
}

func (m *defaultTransactionRecordModel) Delete(ctx context.Context, transactionId string) error {
	query := fmt.Sprintf("delete from %s where `transaction_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, transactionId)
	return err
}

func (m *defaultTransactionRecordModel) FindOne(ctx context.Context, transactionId string) (*TransactionRecord, error) {
	query := fmt.Sprintf("select %s from %s where `transaction_id` = ? limit 1", transactionRecordRows, m.table)
	var resp TransactionRecord
	err := m.conn.QueryRowCtx(ctx, &resp, query, transactionId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTransactionRecordModel) Insert(ctx context.Context, data *TransactionRecord) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, transactionRecordRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.TransactionId, data.AccountFrom, data.AccountTo, data.TransactionType, data.Amount, data.Status)
	return ret, err
}

func (m *defaultTransactionRecordModel) Update(ctx context.Context, data *TransactionRecord) error {
	query := fmt.Sprintf("update %s set %s where `transaction_id` = ?", m.table, transactionRecordRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.AccountFrom, data.AccountTo, data.TransactionType, data.Amount, data.Status, data.TransactionId)
	return err
}

func (m *defaultTransactionRecordModel) tableName() string {
	return m.table
}
