// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	accountFieldNames          = builder.RawFieldNames(&Account{})
	accountRows                = strings.Join(accountFieldNames, ",")
	accountRowsExpectAutoSet   = strings.Join(stringx.Remove(accountFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	accountRowsWithPlaceHolder = strings.Join(stringx.Remove(accountFieldNames, "`account_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	accountModel interface {
		Insert(ctx context.Context, data *Account) (sql.Result, error)
		FindOne(ctx context.Context, accountId string) (*Account, error)
		Update(ctx context.Context, data *Account) error
		Delete(ctx context.Context, accountId string) error
	}

	defaultAccountModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Account struct {
		AccountId   string    `db:"account_id"`
		AccountType int64     `db:"account_type"`
		CustomerId  string    `db:"customer_id"`
		Password    string    `db:"password"`
		Balance     float64   `db:"balance"`
		Status      int64     `db:"status"`
		CreatedAt   time.Time `db:"created_at"`
		UpdatedAt   time.Time `db:"updated_at"`
	}
)

func newAccountModel(conn sqlx.SqlConn) *defaultAccountModel {
	return &defaultAccountModel{
		conn:  conn,
		table: "`account`",
	}
}

func (m *defaultAccountModel) Delete(ctx context.Context, accountId string) error {
	query := fmt.Sprintf("delete from %s where `account_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, accountId)
	return err
}

func (m *defaultAccountModel) FindOne(ctx context.Context, accountId string) (*Account, error) {
	query := fmt.Sprintf("select %s from %s where `account_id` = ? limit 1", accountRows, m.table)
	var resp Account
	err := m.conn.QueryRowCtx(ctx, &resp, query, accountId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAccountModel) Insert(ctx context.Context, data *Account) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, accountRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.AccountId, data.AccountType, data.CustomerId, data.Password, data.Balance, data.Status)
	return ret, err
}

func (m *defaultAccountModel) Update(ctx context.Context, data *Account) error {
	query := fmt.Sprintf("update %s set %s where `account_id` = ?", m.table, accountRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.AccountType, data.CustomerId, data.Password, data.Balance, data.Status, data.AccountId)
	return err
}

func (m *defaultAccountModel) tableName() string {
	return m.table
}
