// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	customerIndividualFieldNames          = builder.RawFieldNames(&CustomerIndividual{})
	customerIndividualRows                = strings.Join(customerIndividualFieldNames, ",")
	customerIndividualRowsExpectAutoSet   = strings.Join(stringx.Remove(customerIndividualFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	customerIndividualRowsWithPlaceHolder = strings.Join(stringx.Remove(customerIndividualFieldNames, "`id_card`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	customerIndividualModel interface {
		Insert(ctx context.Context, data *CustomerIndividual) (sql.Result, error)
		FindOne(ctx context.Context, idCard string) (*CustomerIndividual, error)
		FindOneByEmail(ctx context.Context, email string) (*CustomerIndividual, error)
		FindOneByPhone(ctx context.Context, phone string) (*CustomerIndividual, error)
		Update(ctx context.Context, data *CustomerIndividual) error
		Delete(ctx context.Context, idCard string) error
	}

	defaultCustomerIndividualModel struct {
		conn  sqlx.SqlConn
		table string
	}

	CustomerIndividual struct {
		IdCard    string    `db:"id_card"`
		Name      string    `db:"name"`
		Email     string    `db:"email"`
		Phone     string    `db:"phone"`
		CreatedAt time.Time `db:"created_at"`
		UpdatedAt time.Time `db:"updated_at"`
	}
)

func newCustomerIndividualModel(conn sqlx.SqlConn) *defaultCustomerIndividualModel {
	return &defaultCustomerIndividualModel{
		conn:  conn,
		table: "`customer_individual`",
	}
}

func (m *defaultCustomerIndividualModel) Delete(ctx context.Context, idCard string) error {
	query := fmt.Sprintf("delete from %s where `id_card` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, idCard)
	return err
}

func (m *defaultCustomerIndividualModel) FindOne(ctx context.Context, idCard string) (*CustomerIndividual, error) {
	query := fmt.Sprintf("select %s from %s where `id_card` = ? limit 1", customerIndividualRows, m.table)
	var resp CustomerIndividual
	err := m.conn.QueryRowCtx(ctx, &resp, query, idCard)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCustomerIndividualModel) FindOneByEmail(ctx context.Context, email string) (*CustomerIndividual, error) {
	var resp CustomerIndividual
	query := fmt.Sprintf("select %s from %s where `email` = ? limit 1", customerIndividualRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, email)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCustomerIndividualModel) FindOneByPhone(ctx context.Context, phone string) (*CustomerIndividual, error) {
	var resp CustomerIndividual
	query := fmt.Sprintf("select %s from %s where `phone` = ? limit 1", customerIndividualRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, phone)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCustomerIndividualModel) Insert(ctx context.Context, data *CustomerIndividual) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, customerIndividualRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.IdCard, data.Name, data.Email, data.Phone)
	return ret, err
}

func (m *defaultCustomerIndividualModel) Update(ctx context.Context, newData *CustomerIndividual) error {
	query := fmt.Sprintf("update %s set %s where `id_card` = ?", m.table, customerIndividualRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Name, newData.Email, newData.Phone, newData.IdCard)
	return err
}

func (m *defaultCustomerIndividualModel) tableName() string {
	return m.table
}
