// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	customerEnterpriseFieldNames          = builder.RawFieldNames(&CustomerEnterprise{})
	customerEnterpriseRows                = strings.Join(customerEnterpriseFieldNames, ",")
	customerEnterpriseRowsExpectAutoSet   = strings.Join(stringx.Remove(customerEnterpriseFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	customerEnterpriseRowsWithPlaceHolder = strings.Join(stringx.Remove(customerEnterpriseFieldNames, "`credit_code`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	customerEnterpriseModel interface {
		Insert(ctx context.Context, data *CustomerEnterprise) (sql.Result, error)
		FindOne(ctx context.Context, creditCode string) (*CustomerEnterprise, error)
		FindOneByEmail(ctx context.Context, email string) (*CustomerEnterprise, error)
		FindOneByPhone(ctx context.Context, phone string) (*CustomerEnterprise, error)
		Update(ctx context.Context, data *CustomerEnterprise) error
		Delete(ctx context.Context, creditCode string) error
	}

	defaultCustomerEnterpriseModel struct {
		conn  sqlx.SqlConn
		table string
	}

	CustomerEnterprise struct {
		CreditCode  string    `db:"credit_code"`
		CompanyName string    `db:"company_name"`
		LegalIdCard string    `db:"legal_id_card"`
		LegalName   string    `db:"legal_name"`
		Email       string    `db:"email"`
		Phone       string    `db:"phone"`
		CreatedAt   time.Time `db:"created_at"`
		UpdatedAt   time.Time `db:"updated_at"`
	}
)

func newCustomerEnterpriseModel(conn sqlx.SqlConn) *defaultCustomerEnterpriseModel {
	return &defaultCustomerEnterpriseModel{
		conn:  conn,
		table: "`customer_enterprise`",
	}
}

func (m *defaultCustomerEnterpriseModel) Delete(ctx context.Context, creditCode string) error {
	query := fmt.Sprintf("delete from %s where `credit_code` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, creditCode)
	return err
}

func (m *defaultCustomerEnterpriseModel) FindOne(ctx context.Context, creditCode string) (*CustomerEnterprise, error) {
	query := fmt.Sprintf("select %s from %s where `credit_code` = ? limit 1", customerEnterpriseRows, m.table)
	var resp CustomerEnterprise
	err := m.conn.QueryRowCtx(ctx, &resp, query, creditCode)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCustomerEnterpriseModel) FindOneByEmail(ctx context.Context, email string) (*CustomerEnterprise, error) {
	var resp CustomerEnterprise
	query := fmt.Sprintf("select %s from %s where `email` = ? limit 1", customerEnterpriseRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, email)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCustomerEnterpriseModel) FindOneByPhone(ctx context.Context, phone string) (*CustomerEnterprise, error) {
	var resp CustomerEnterprise
	query := fmt.Sprintf("select %s from %s where `phone` = ? limit 1", customerEnterpriseRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, phone)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCustomerEnterpriseModel) Insert(ctx context.Context, data *CustomerEnterprise) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, customerEnterpriseRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.CreditCode, data.CompanyName, data.LegalIdCard, data.LegalName, data.Email, data.Phone)
	return ret, err
}

func (m *defaultCustomerEnterpriseModel) Update(ctx context.Context, newData *CustomerEnterprise) error {
	query := fmt.Sprintf("update %s set %s where `credit_code` = ?", m.table, customerEnterpriseRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.CompanyName, newData.LegalIdCard, newData.LegalName, newData.Email, newData.Phone, newData.CreditCode)
	return err
}

func (m *defaultCustomerEnterpriseModel) tableName() string {
	return m.table
}
