// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type DepositRequest struct {
	Amount float64 `json:"amount"`
}

type DepositResponse struct {
	TransactionID string  `json:"transaction_id"`
	AccountID     string  `json:"account_id"`
	Balance       float64 `json:"balance"`
}

type TransferRequest struct {
	AccountTo string  `json:"account_to"`
	Amount    float64 `json:"amount"`
}

type TransferResponse struct {
	TransactionID string  `json:"transaction_id"`
	AccountFrom   string  `json:"account_from"`
	AccountTo     string  `json:"account_to"`
	Amount        float64 `json:"amount"`
}

type WithdrawRequest struct {
	Amount float64 `json:"amount"`
}

type WithdrawResponse struct {
	TransactionID string  `json:"transaction_id"`
	AccountID     string  `json:"account_id"`
	Balance       float64 `json:"balance"`
}
