// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	transaction "github.com/Drengin6306/ZeroBank/service/transaction/api/internal/handler/transaction"
	"github.com/Drengin6306/ZeroBank/service/transaction/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/deposit",
				Handler: transaction.DepositHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/transaction",
				Handler: transaction.TransactionHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/withdraw",
				Handler: transaction.WithdrawHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)
}
