// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: riskcontrol.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RiskCheckRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionId   string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	AccountFrom     string                 `protobuf:"bytes,2,opt,name=account_from,json=accountFrom,proto3" json:"account_from,omitempty"`
	AccountTo       string                 `protobuf:"bytes,3,opt,name=account_to,json=accountTo,proto3" json:"account_to,omitempty"`
	AccountType     int32                  `protobuf:"varint,4,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	Amount          float64                `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	TransactionType int32                  `protobuf:"varint,6,opt,name=transaction_type,json=transactionType,proto3" json:"transaction_type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RiskCheckRequest) Reset() {
	*x = RiskCheckRequest{}
	mi := &file_riskcontrol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskCheckRequest) ProtoMessage() {}

func (x *RiskCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_riskcontrol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskCheckRequest.ProtoReflect.Descriptor instead.
func (*RiskCheckRequest) Descriptor() ([]byte, []int) {
	return file_riskcontrol_proto_rawDescGZIP(), []int{0}
}

func (x *RiskCheckRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *RiskCheckRequest) GetAccountFrom() string {
	if x != nil {
		return x.AccountFrom
	}
	return ""
}

func (x *RiskCheckRequest) GetAccountTo() string {
	if x != nil {
		return x.AccountTo
	}
	return ""
}

func (x *RiskCheckRequest) GetAccountType() int32 {
	if x != nil {
		return x.AccountType
	}
	return 0
}

func (x *RiskCheckRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RiskCheckRequest) GetTransactionType() int32 {
	if x != nil {
		return x.TransactionType
	}
	return 0
}

type RiskCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Passed        bool                   `protobuf:"varint,1,opt,name=passed,proto3" json:"passed,omitempty"`
	Reason        int32                  `protobuf:"varint,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskCheckResponse) Reset() {
	*x = RiskCheckResponse{}
	mi := &file_riskcontrol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskCheckResponse) ProtoMessage() {}

func (x *RiskCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_riskcontrol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskCheckResponse.ProtoReflect.Descriptor instead.
func (*RiskCheckResponse) Descriptor() ([]byte, []int) {
	return file_riskcontrol_proto_rawDescGZIP(), []int{1}
}

func (x *RiskCheckResponse) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *RiskCheckResponse) GetReason() int32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

var File_riskcontrol_proto protoreflect.FileDescriptor

const file_riskcontrol_proto_rawDesc = "" +
	"\n" +
	"\x11riskcontrol.proto\x12\vriskcontrol\"\xe1\x01\n" +
	"\x10RiskCheckRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12!\n" +
	"\faccount_from\x18\x02 \x01(\tR\vaccountFrom\x12\x1d\n" +
	"\n" +
	"account_to\x18\x03 \x01(\tR\taccountTo\x12!\n" +
	"\faccount_type\x18\x04 \x01(\x05R\vaccountType\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x01R\x06amount\x12)\n" +
	"\x10transaction_type\x18\x06 \x01(\x05R\x0ftransactionType\"C\n" +
	"\x11RiskCheckResponse\x12\x16\n" +
	"\x06passed\x18\x01 \x01(\bR\x06passed\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\x05R\x06reason2g\n" +
	"\x12RiskControlService\x12Q\n" +
	"\x10CheckTransaction\x12\x1d.riskcontrol.RiskCheckRequest\x1a\x1e.riskcontrol.RiskCheckResponseB\bZ\x06/protob\x06proto3"

var (
	file_riskcontrol_proto_rawDescOnce sync.Once
	file_riskcontrol_proto_rawDescData []byte
)

func file_riskcontrol_proto_rawDescGZIP() []byte {
	file_riskcontrol_proto_rawDescOnce.Do(func() {
		file_riskcontrol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_riskcontrol_proto_rawDesc), len(file_riskcontrol_proto_rawDesc)))
	})
	return file_riskcontrol_proto_rawDescData
}

var file_riskcontrol_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_riskcontrol_proto_goTypes = []any{
	(*RiskCheckRequest)(nil),  // 0: riskcontrol.RiskCheckRequest
	(*RiskCheckResponse)(nil), // 1: riskcontrol.RiskCheckResponse
}
var file_riskcontrol_proto_depIdxs = []int32{
	0, // 0: riskcontrol.RiskControlService.CheckTransaction:input_type -> riskcontrol.RiskCheckRequest
	1, // 1: riskcontrol.RiskControlService.CheckTransaction:output_type -> riskcontrol.RiskCheckResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_riskcontrol_proto_init() }
func file_riskcontrol_proto_init() {
	if File_riskcontrol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_riskcontrol_proto_rawDesc), len(file_riskcontrol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_riskcontrol_proto_goTypes,
		DependencyIndexes: file_riskcontrol_proto_depIdxs,
		MessageInfos:      file_riskcontrol_proto_msgTypes,
	}.Build()
	File_riskcontrol_proto = out.File
	file_riskcontrol_proto_goTypes = nil
	file_riskcontrol_proto_depIdxs = nil
}
