// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.2
// source: riskcontrol.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RiskControlService_CheckTransaction_FullMethodName = "/riskcontrol.RiskControlService/CheckTransaction"
)

// RiskControlServiceClient is the client API for RiskControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 风控服务
type RiskControlServiceClient interface {
	// 检查交易风险
	CheckTransaction(ctx context.Context, in *RiskCheckRequest, opts ...grpc.CallOption) (*RiskCheckResponse, error)
}

type riskControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRiskControlServiceClient(cc grpc.ClientConnInterface) RiskControlServiceClient {
	return &riskControlServiceClient{cc}
}

func (c *riskControlServiceClient) CheckTransaction(ctx context.Context, in *RiskCheckRequest, opts ...grpc.CallOption) (*RiskCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RiskCheckResponse)
	err := c.cc.Invoke(ctx, RiskControlService_CheckTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RiskControlServiceServer is the server API for RiskControlService service.
// All implementations must embed UnimplementedRiskControlServiceServer
// for forward compatibility.
//
// 风控服务
type RiskControlServiceServer interface {
	// 检查交易风险
	CheckTransaction(context.Context, *RiskCheckRequest) (*RiskCheckResponse, error)
	mustEmbedUnimplementedRiskControlServiceServer()
}

// UnimplementedRiskControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRiskControlServiceServer struct{}

func (UnimplementedRiskControlServiceServer) CheckTransaction(context.Context, *RiskCheckRequest) (*RiskCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckTransaction not implemented")
}
func (UnimplementedRiskControlServiceServer) mustEmbedUnimplementedRiskControlServiceServer() {}
func (UnimplementedRiskControlServiceServer) testEmbeddedByValue()                            {}

// UnsafeRiskControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RiskControlServiceServer will
// result in compilation errors.
type UnsafeRiskControlServiceServer interface {
	mustEmbedUnimplementedRiskControlServiceServer()
}

func RegisterRiskControlServiceServer(s grpc.ServiceRegistrar, srv RiskControlServiceServer) {
	// If the following call pancis, it indicates UnimplementedRiskControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RiskControlService_ServiceDesc, srv)
}

func _RiskControlService_CheckTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RiskCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskControlServiceServer).CheckTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskControlService_CheckTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskControlServiceServer).CheckTransaction(ctx, req.(*RiskCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RiskControlService_ServiceDesc is the grpc.ServiceDesc for RiskControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RiskControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "riskcontrol.RiskControlService",
	HandlerType: (*RiskControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckTransaction",
			Handler:    _RiskControlService_CheckTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "riskcontrol.proto",
}
