// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.2
// source: riskcontrol.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RiskControl_CheckTransaction_FullMethodName = "/riskcontrol.RiskControl/CheckTransaction"
)

// RiskControlClient is the client API for RiskControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 风控服务
type RiskControlClient interface {
	// 检查交易风险
	CheckTransaction(ctx context.Context, in *RiskCheckRequest, opts ...grpc.CallOption) (*RiskCheckResponse, error)
}

type riskControlClient struct {
	cc grpc.ClientConnInterface
}

func NewRiskControlClient(cc grpc.ClientConnInterface) RiskControlClient {
	return &riskControlClient{cc}
}

func (c *riskControlClient) CheckTransaction(ctx context.Context, in *RiskCheckRequest, opts ...grpc.CallOption) (*RiskCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RiskCheckResponse)
	err := c.cc.Invoke(ctx, RiskControl_CheckTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RiskControlServer is the server API for RiskControl service.
// All implementations must embed UnimplementedRiskControlServer
// for forward compatibility.
//
// 风控服务
type RiskControlServer interface {
	// 检查交易风险
	CheckTransaction(context.Context, *RiskCheckRequest) (*RiskCheckResponse, error)
	mustEmbedUnimplementedRiskControlServer()
}

// UnimplementedRiskControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRiskControlServer struct{}

func (UnimplementedRiskControlServer) CheckTransaction(context.Context, *RiskCheckRequest) (*RiskCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckTransaction not implemented")
}
func (UnimplementedRiskControlServer) mustEmbedUnimplementedRiskControlServer() {}
func (UnimplementedRiskControlServer) testEmbeddedByValue()                     {}

// UnsafeRiskControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RiskControlServer will
// result in compilation errors.
type UnsafeRiskControlServer interface {
	mustEmbedUnimplementedRiskControlServer()
}

func RegisterRiskControlServer(s grpc.ServiceRegistrar, srv RiskControlServer) {
	// If the following call pancis, it indicates UnimplementedRiskControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RiskControl_ServiceDesc, srv)
}

func _RiskControl_CheckTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RiskCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskControlServer).CheckTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskControl_CheckTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskControlServer).CheckTransaction(ctx, req.(*RiskCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RiskControl_ServiceDesc is the grpc.ServiceDesc for RiskControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RiskControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "riskcontrol.RiskControl",
	HandlerType: (*RiskControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckTransaction",
			Handler:    _RiskControl_CheckTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "riskcontrol.proto",
}
