// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: riskcontrol.proto

package riskcontrolservice

import (
	"context"

	"github.com/Drengin6306/ZeroBank/service/riskcontrol/rpc/proto"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	RiskCheckRequest  = proto.RiskCheckRequest
	RiskCheckResponse = proto.RiskCheckResponse

	RiskControlService interface {
		// 检查交易风险
		CheckTransaction(ctx context.Context, in *RiskCheckRequest, opts ...grpc.CallOption) (*RiskCheckResponse, error)
	}

	defaultRiskControlService struct {
		cli zrpc.Client
	}
)

func NewRiskControlService(cli zrpc.Client) RiskControlService {
	return &defaultRiskControlService{
		cli: cli,
	}
}

// 检查交易风险
func (m *defaultRiskControlService) CheckTransaction(ctx context.Context, in *RiskCheckRequest, opts ...grpc.CallOption) (*RiskCheckResponse, error) {
	client := proto.NewRiskControlServiceClient(m.cli.Conn())
	return client.CheckTransaction(ctx, in, opts...)
}
