// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package mysql

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	limitAmountFieldNames          = builder.RawFieldNames(&LimitAmount{})
	limitAmountRows                = strings.Join(limitAmountFieldNames, ",")
	limitAmountRowsExpectAutoSet   = strings.Join(stringx.Remove(limitAmountFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	limitAmountRowsWithPlaceHolder = strings.Join(stringx.Remove(limitAmountFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	limitAmountModel interface {
		Insert(ctx context.Context, data *LimitAmount) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*LimitAmount, error)
		Update(ctx context.Context, data *LimitAmount) error
		Delete(ctx context.Context, id int64) error
	}

	defaultLimitAmountModel struct {
		conn  sqlx.SqlConn
		table string
	}

	LimitAmount struct {
		Id          int64     `db:"id"`
		AccountType int64     `db:"account_type"`
		LimitType   int64     `db:"limit_type"`
		Amount      float64   `db:"amount"`
		UpdatedAt   time.Time `db:"updated_at"`
	}
)

func newLimitAmountModel(conn sqlx.SqlConn) *defaultLimitAmountModel {
	return &defaultLimitAmountModel{
		conn:  conn,
		table: "`limit_amount`",
	}
}

func (m *defaultLimitAmountModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultLimitAmountModel) FindOne(ctx context.Context, id int64) (*LimitAmount, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", limitAmountRows, m.table)
	var resp LimitAmount
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLimitAmountModel) Insert(ctx context.Context, data *LimitAmount) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, limitAmountRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.AccountType, data.LimitType, data.Amount)
	return ret, err
}

func (m *defaultLimitAmountModel) Update(ctx context.Context, data *LimitAmount) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, limitAmountRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.AccountType, data.LimitType, data.Amount, data.Id)
	return err
}

func (m *defaultLimitAmountModel) tableName() string {
	return m.table
}
