// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package mysql

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	riskRecordFieldNames          = builder.RawFieldNames(&RiskRecord{})
	riskRecordRows                = strings.Join(riskRecordFieldNames, ",")
	riskRecordRowsExpectAutoSet   = strings.Join(stringx.Remove(riskRecordFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	riskRecordRowsWithPlaceHolder = strings.Join(stringx.Remove(riskRecordFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	riskRecordModel interface {
		Insert(ctx context.Context, data *RiskRecord) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*RiskRecord, error)
		Update(ctx context.Context, data *RiskRecord) error
		Delete(ctx context.Context, id int64) error
	}

	defaultRiskRecordModel struct {
		conn  sqlx.SqlConn
		table string
	}

	RiskRecord struct {
		Id            int64     `db:"id"`
		AccountId     string    `db:"account_id"`
		TransactionId string    `db:"transaction_id"`
		RiskType      int64     `db:"risk_type"`
		CreatedAt     time.Time `db:"created_at"`
	}
)

func newRiskRecordModel(conn sqlx.SqlConn) *defaultRiskRecordModel {
	return &defaultRiskRecordModel{
		conn:  conn,
		table: "`risk_record`",
	}
}

func (m *defaultRiskRecordModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultRiskRecordModel) FindOne(ctx context.Context, id int64) (*RiskRecord, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", riskRecordRows, m.table)
	var resp RiskRecord
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRiskRecordModel) Insert(ctx context.Context, data *RiskRecord) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, riskRecordRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.AccountId, data.TransactionId, data.RiskType)
	return ret, err
}

func (m *defaultRiskRecordModel) Update(ctx context.Context, data *RiskRecord) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, riskRecordRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.AccountId, data.TransactionId, data.RiskType, data.Id)
	return err
}

func (m *defaultRiskRecordModel) tableName() string {
	return m.table
}
