// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: transaction.proto

package transaction

import (
	"context"

	"github.com/Drengin6306/ZeroBank/service/transaction/rpc/proto"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Record              = proto.Record
	TransactionRequest  = proto.TransactionRequest
	TransactionResponse = proto.TransactionResponse

	Transaction interface {
		// 获取交易流水
		GetTransactions(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionResponse, error)
	}

	defaultTransaction struct {
		cli zrpc.Client
	}
)

func NewTransaction(cli zrpc.Client) Transaction {
	return &defaultTransaction{
		cli: cli,
	}
}

// 获取交易流水
func (m *defaultTransaction) GetTransactions(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionResponse, error) {
	client := proto.NewTransactionClient(m.cli.Conn())
	return client.GetTransactions(ctx, in, opts...)
}
