// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: account.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountInfoRequest) Reset() {
	*x = AccountInfoRequest{}
	mi := &file_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountInfoRequest) ProtoMessage() {}

func (x *AccountInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountInfoRequest.ProtoReflect.Descriptor instead.
func (*AccountInfoRequest) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{0}
}

func (x *AccountInfoRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type AccountInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 账户类型 0:个人 1:企业
	AccountType int32 `protobuf:"varint,1,opt,name=accountType,proto3" json:"accountType,omitempty"`
	// 余额
	Balance float64 `protobuf:"fixed64,2,opt,name=balance,proto3" json:"balance,omitempty"`
	// 个人用户信息
	//
	// Types that are valid to be assigned to UserInfo:
	//
	//	*AccountInfoResponse_CustomerUserInfo
	//	*AccountInfoResponse_EnterpriseUserInfo
	UserInfo      isAccountInfoResponse_UserInfo `protobuf_oneof:"userInfo"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountInfoResponse) Reset() {
	*x = AccountInfoResponse{}
	mi := &file_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountInfoResponse) ProtoMessage() {}

func (x *AccountInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountInfoResponse.ProtoReflect.Descriptor instead.
func (*AccountInfoResponse) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{1}
}

func (x *AccountInfoResponse) GetAccountType() int32 {
	if x != nil {
		return x.AccountType
	}
	return 0
}

func (x *AccountInfoResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *AccountInfoResponse) GetUserInfo() isAccountInfoResponse_UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

func (x *AccountInfoResponse) GetCustomerUserInfo() *CustomerUserInfo {
	if x != nil {
		if x, ok := x.UserInfo.(*AccountInfoResponse_CustomerUserInfo); ok {
			return x.CustomerUserInfo
		}
	}
	return nil
}

func (x *AccountInfoResponse) GetEnterpriseUserInfo() *EnterpriseUserInfo {
	if x != nil {
		if x, ok := x.UserInfo.(*AccountInfoResponse_EnterpriseUserInfo); ok {
			return x.EnterpriseUserInfo
		}
	}
	return nil
}

type isAccountInfoResponse_UserInfo interface {
	isAccountInfoResponse_UserInfo()
}

type AccountInfoResponse_CustomerUserInfo struct {
	CustomerUserInfo *CustomerUserInfo `protobuf:"bytes,3,opt,name=customerUserInfo,proto3,oneof"`
}

type AccountInfoResponse_EnterpriseUserInfo struct {
	EnterpriseUserInfo *EnterpriseUserInfo `protobuf:"bytes,4,opt,name=enterpriseUserInfo,proto3,oneof"`
}

func (*AccountInfoResponse_CustomerUserInfo) isAccountInfoResponse_UserInfo() {}

func (*AccountInfoResponse_EnterpriseUserInfo) isAccountInfoResponse_UserInfo() {}

type CustomerUserInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 账户ID
	AccountID string `protobuf:"bytes,1,opt,name=accountID,proto3" json:"accountID,omitempty"`
	// 姓名
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 邮箱
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// 电话
	Phone         string `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomerUserInfo) Reset() {
	*x = CustomerUserInfo{}
	mi := &file_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerUserInfo) ProtoMessage() {}

func (x *CustomerUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerUserInfo.ProtoReflect.Descriptor instead.
func (*CustomerUserInfo) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{2}
}

func (x *CustomerUserInfo) GetAccountID() string {
	if x != nil {
		return x.AccountID
	}
	return ""
}

func (x *CustomerUserInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CustomerUserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CustomerUserInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type EnterpriseUserInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 账户ID
	AccountID string `protobuf:"bytes,1,opt,name=accountID,proto3" json:"accountID,omitempty"`
	// 企业名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 企业社会信用代码
	CreditCode string `protobuf:"bytes,3,opt,name=creditCode,proto3" json:"creditCode,omitempty"`
	// 法人姓名
	LegalName string `protobuf:"bytes,4,opt,name=legalName,proto3" json:"legalName,omitempty"`
	// 电话
	Phone string `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	// 邮箱
	Email         string `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterpriseUserInfo) Reset() {
	*x = EnterpriseUserInfo{}
	mi := &file_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterpriseUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterpriseUserInfo) ProtoMessage() {}

func (x *EnterpriseUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterpriseUserInfo.ProtoReflect.Descriptor instead.
func (*EnterpriseUserInfo) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{3}
}

func (x *EnterpriseUserInfo) GetAccountID() string {
	if x != nil {
		return x.AccountID
	}
	return ""
}

func (x *EnterpriseUserInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnterpriseUserInfo) GetCreditCode() string {
	if x != nil {
		return x.CreditCode
	}
	return ""
}

func (x *EnterpriseUserInfo) GetLegalName() string {
	if x != nil {
		return x.LegalName
	}
	return ""
}

func (x *EnterpriseUserInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *EnterpriseUserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type QueryAccountBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAccountBalanceRequest) Reset() {
	*x = QueryAccountBalanceRequest{}
	mi := &file_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAccountBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAccountBalanceRequest) ProtoMessage() {}

func (x *QueryAccountBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAccountBalanceRequest.ProtoReflect.Descriptor instead.
func (*QueryAccountBalanceRequest) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{4}
}

func (x *QueryAccountBalanceRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type QueryAccountBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Balance       float64                `protobuf:"fixed64,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAccountBalanceResponse) Reset() {
	*x = QueryAccountBalanceResponse{}
	mi := &file_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAccountBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAccountBalanceResponse) ProtoMessage() {}

func (x *QueryAccountBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAccountBalanceResponse.ProtoReflect.Descriptor instead.
func (*QueryAccountBalanceResponse) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{5}
}

func (x *QueryAccountBalanceResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *QueryAccountBalanceResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type DeductBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductBalanceRequest) Reset() {
	*x = DeductBalanceRequest{}
	mi := &file_account_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductBalanceRequest) ProtoMessage() {}

func (x *DeductBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductBalanceRequest.ProtoReflect.Descriptor instead.
func (*DeductBalanceRequest) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{6}
}

func (x *DeductBalanceRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *DeductBalanceRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type DeductBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Balance       float64                `protobuf:"fixed64,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductBalanceResponse) Reset() {
	*x = DeductBalanceResponse{}
	mi := &file_account_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductBalanceResponse) ProtoMessage() {}

func (x *DeductBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductBalanceResponse.ProtoReflect.Descriptor instead.
func (*DeductBalanceResponse) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{7}
}

func (x *DeductBalanceResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *DeductBalanceResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type AddBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBalanceRequest) Reset() {
	*x = AddBalanceRequest{}
	mi := &file_account_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBalanceRequest) ProtoMessage() {}

func (x *AddBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBalanceRequest.ProtoReflect.Descriptor instead.
func (*AddBalanceRequest) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{8}
}

func (x *AddBalanceRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AddBalanceRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type AddBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Balance       float64                `protobuf:"fixed64,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBalanceResponse) Reset() {
	*x = AddBalanceResponse{}
	mi := &file_account_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBalanceResponse) ProtoMessage() {}

func (x *AddBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBalanceResponse.ProtoReflect.Descriptor instead.
func (*AddBalanceResponse) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{9}
}

func (x *AddBalanceResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AddBalanceResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type IsAccountExistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exist         bool                   `protobuf:"varint,1,opt,name=exist,proto3" json:"exist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsAccountExistResponse) Reset() {
	*x = IsAccountExistResponse{}
	mi := &file_account_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsAccountExistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAccountExistResponse) ProtoMessage() {}

func (x *IsAccountExistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAccountExistResponse.ProtoReflect.Descriptor instead.
func (*IsAccountExistResponse) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{10}
}

func (x *IsAccountExistResponse) GetExist() bool {
	if x != nil {
		return x.Exist
	}
	return false
}

var File_account_proto protoreflect.FileDescriptor

const file_account_proto_rawDesc = "" +
	"\n" +
	"\raccount.proto\x12\aaccount\"3\n" +
	"\x12AccountInfoRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"\xf5\x01\n" +
	"\x13AccountInfoResponse\x12 \n" +
	"\vaccountType\x18\x01 \x01(\x05R\vaccountType\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x01R\abalance\x12G\n" +
	"\x10customerUserInfo\x18\x03 \x01(\v2\x19.account.CustomerUserInfoH\x00R\x10customerUserInfo\x12M\n" +
	"\x12enterpriseUserInfo\x18\x04 \x01(\v2\x1b.account.EnterpriseUserInfoH\x00R\x12enterpriseUserInfoB\n" +
	"\n" +
	"\buserInfo\"p\n" +
	"\x10CustomerUserInfo\x12\x1c\n" +
	"\taccountID\x18\x01 \x01(\tR\taccountID\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\"\xb0\x01\n" +
	"\x12EnterpriseUserInfo\x12\x1c\n" +
	"\taccountID\x18\x01 \x01(\tR\taccountID\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"creditCode\x18\x03 \x01(\tR\n" +
	"creditCode\x12\x1c\n" +
	"\tlegalName\x18\x04 \x01(\tR\tlegalName\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\";\n" +
	"\x1aQueryAccountBalanceRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"V\n" +
	"\x1bQueryAccountBalanceResponse\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x01R\abalance\"M\n" +
	"\x14DeductBalanceRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\"P\n" +
	"\x15DeductBalanceResponse\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x01R\abalance\"J\n" +
	"\x11AddBalanceRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\"M\n" +
	"\x12AddBalanceResponse\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x01R\abalance\".\n" +
	"\x16IsAccountExistResponse\x12\x14\n" +
	"\x05exist\x18\x01 \x01(\bR\x05exist2\x9f\x03\n" +
	"\aAccount\x12K\n" +
	"\x0eGetAccountInfo\x12\x1b.account.AccountInfoRequest\x1a\x1c.account.AccountInfoResponse\x12`\n" +
	"\x13QueryAccountBalance\x12#.account.QueryAccountBalanceRequest\x1a$.account.QueryAccountBalanceResponse\x12N\n" +
	"\rDeductBalance\x12\x1d.account.DeductBalanceRequest\x1a\x1e.account.DeductBalanceResponse\x12E\n" +
	"\n" +
	"AddBalance\x12\x1a.account.AddBalanceRequest\x1a\x1b.account.AddBalanceResponse\x12N\n" +
	"\x0eIsAccountExist\x12\x1b.account.AccountInfoRequest\x1a\x1f.account.IsAccountExistResponseB\bZ\x06/protob\x06proto3"

var (
	file_account_proto_rawDescOnce sync.Once
	file_account_proto_rawDescData []byte
)

func file_account_proto_rawDescGZIP() []byte {
	file_account_proto_rawDescOnce.Do(func() {
		file_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_proto_rawDesc), len(file_account_proto_rawDesc)))
	})
	return file_account_proto_rawDescData
}

var file_account_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_account_proto_goTypes = []any{
	(*AccountInfoRequest)(nil),          // 0: account.AccountInfoRequest
	(*AccountInfoResponse)(nil),         // 1: account.AccountInfoResponse
	(*CustomerUserInfo)(nil),            // 2: account.CustomerUserInfo
	(*EnterpriseUserInfo)(nil),          // 3: account.EnterpriseUserInfo
	(*QueryAccountBalanceRequest)(nil),  // 4: account.QueryAccountBalanceRequest
	(*QueryAccountBalanceResponse)(nil), // 5: account.QueryAccountBalanceResponse
	(*DeductBalanceRequest)(nil),        // 6: account.DeductBalanceRequest
	(*DeductBalanceResponse)(nil),       // 7: account.DeductBalanceResponse
	(*AddBalanceRequest)(nil),           // 8: account.AddBalanceRequest
	(*AddBalanceResponse)(nil),          // 9: account.AddBalanceResponse
	(*IsAccountExistResponse)(nil),      // 10: account.IsAccountExistResponse
}
var file_account_proto_depIdxs = []int32{
	2,  // 0: account.AccountInfoResponse.customerUserInfo:type_name -> account.CustomerUserInfo
	3,  // 1: account.AccountInfoResponse.enterpriseUserInfo:type_name -> account.EnterpriseUserInfo
	0,  // 2: account.Account.GetAccountInfo:input_type -> account.AccountInfoRequest
	4,  // 3: account.Account.QueryAccountBalance:input_type -> account.QueryAccountBalanceRequest
	6,  // 4: account.Account.DeductBalance:input_type -> account.DeductBalanceRequest
	8,  // 5: account.Account.AddBalance:input_type -> account.AddBalanceRequest
	0,  // 6: account.Account.IsAccountExist:input_type -> account.AccountInfoRequest
	1,  // 7: account.Account.GetAccountInfo:output_type -> account.AccountInfoResponse
	5,  // 8: account.Account.QueryAccountBalance:output_type -> account.QueryAccountBalanceResponse
	7,  // 9: account.Account.DeductBalance:output_type -> account.DeductBalanceResponse
	9,  // 10: account.Account.AddBalance:output_type -> account.AddBalanceResponse
	10, // 11: account.Account.IsAccountExist:output_type -> account.IsAccountExistResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_account_proto_init() }
func file_account_proto_init() {
	if File_account_proto != nil {
		return
	}
	file_account_proto_msgTypes[1].OneofWrappers = []any{
		(*AccountInfoResponse_CustomerUserInfo)(nil),
		(*AccountInfoResponse_EnterpriseUserInfo)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_proto_rawDesc), len(file_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_account_proto_goTypes,
		DependencyIndexes: file_account_proto_depIdxs,
		MessageInfos:      file_account_proto_msgTypes,
	}.Build()
	File_account_proto = out.File
	file_account_proto_goTypes = nil
	file_account_proto_depIdxs = nil
}
