// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type BalanceResponse struct {
	Balance float64 `json:"balance"`
}

type CustomerRegisterRequest struct {
	IdCard     string `json:"id_card"`
	Name       string `json:"name"`
	Phone      string `json:"phone"`
	Email      string `json:"email"`
	Password   string `json:"password"`
	RePassword string `json:"re_password"`
}

type CustomerUserInfo struct {
	AccountID string `json:"account_id"`
	Name      string `json:"name"`
	Email     string `json:"email"`
	Phone     string `json:"phone"`
}

type DepositRequest struct {
	Amount float64 `json:"amount"`
}

type DepositResponse struct {
	Balance float64 `json:"balance"`
}

type EnterpriseRegisterRequest struct {
	CreditCode  string `json:"credit_code"`
	Name        string `json:"name"`
	LegalIdCard string `json:"legal_id_card"`
	LegalName   string `json:"legal_name"`
	Phone       string `json:"phone"`
	Email       string `json:"email"`
	Password    string `json:"password"`
	RePassword  string `json:"re_password"`
}

type EnterpriseUserInfo struct {
	AccountID  string `json:"account_id"`
	Name       string `json:"name"`
	CreditCode string `json:"credit_code"`
	LegalName  string `json:"legal_name"`
	Phone      string `json:"phone"`
	Email      string `json:"email"`
}

type LoginRequest struct {
	AccountID string `json:"account_id"`
	Password  string `json:"password"`
}

type LoginResponse struct {
	Token string `json:"token"`
}

type RegisterResponse struct {
	AccountID string `json:"account_id"`
}

type UserInfoResponse struct {
	AccountType int         `json:"account_type" enum:"0,1"`
	UserInfo    interface{} `json:"user_info"`
}

type WithdrawRequest struct {
	Amount float64 `json:"amount"`
}

type WithdrawResponse struct {
	Balance float64 `json:"balance"`
}
