// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: riskcontrol.proto

package riskcontrol

import (
	"context"

	"github.com/Drengin6306/ZeroBank/service/riskcontrol/rpc/proto"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	RiskCheckRequest  = proto.RiskCheckRequest
	RiskCheckResponse = proto.RiskCheckResponse

	RiskControl interface {
		// 检查交易风险
		CheckTransaction(ctx context.Context, in *RiskCheckRequest, opts ...grpc.CallOption) (*RiskCheckResponse, error)
	}

	defaultRiskControl struct {
		cli zrpc.Client
	}
)

func NewRiskControl(cli zrpc.Client) RiskControl {
	return &defaultRiskControl{
		cli: cli,
	}
}

// 检查交易风险
func (m *defaultRiskControl) CheckTransaction(ctx context.Context, in *RiskCheckRequest, opts ...grpc.CallOption) (*RiskCheckResponse, error) {
	client := proto.NewRiskControlClient(m.cli.Conn())
	return client.CheckTransaction(ctx, in, opts...)
}
