// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: account.proto

package account

import (
	"context"

	"github.com/Drengin6306/ZeroBank/service/account/rpc/proto"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AccountInfoRequest          = proto.AccountInfoRequest
	AccountInfoResponse         = proto.AccountInfoResponse
	AddBalanceRequest           = proto.AddBalanceRequest
	AddBalanceResponse          = proto.AddBalanceResponse
	CustomerUserInfo            = proto.CustomerUserInfo
	DeductBalanceRequest        = proto.DeductBalanceRequest
	DeductBalanceResponse       = proto.DeductBalanceResponse
	EnterpriseUserInfo          = proto.EnterpriseUserInfo
	IsAccountExistResponse      = proto.IsAccountExistResponse
	QueryAccountBalanceRequest  = proto.QueryAccountBalanceRequest
	QueryAccountBalanceResponse = proto.QueryAccountBalanceResponse

	Account interface {
		GetAccountInfo(ctx context.Context, in *AccountInfoRequest, opts ...grpc.CallOption) (*AccountInfoResponse, error)
		QueryAccountBalance(ctx context.Context, in *QueryAccountBalanceRequest, opts ...grpc.CallOption) (*QueryAccountBalanceResponse, error)
		DeductBalance(ctx context.Context, in *DeductBalanceRequest, opts ...grpc.CallOption) (*DeductBalanceResponse, error)
		AddBalance(ctx context.Context, in *AddBalanceRequest, opts ...grpc.CallOption) (*AddBalanceResponse, error)
		IsAccountExist(ctx context.Context, in *AccountInfoRequest, opts ...grpc.CallOption) (*IsAccountExistResponse, error)
	}

	defaultAccount struct {
		cli zrpc.Client
	}
)

func NewAccount(cli zrpc.Client) Account {
	return &defaultAccount{
		cli: cli,
	}
}

func (m *defaultAccount) GetAccountInfo(ctx context.Context, in *AccountInfoRequest, opts ...grpc.CallOption) (*AccountInfoResponse, error) {
	client := proto.NewAccountClient(m.cli.Conn())
	return client.GetAccountInfo(ctx, in, opts...)
}

func (m *defaultAccount) QueryAccountBalance(ctx context.Context, in *QueryAccountBalanceRequest, opts ...grpc.CallOption) (*QueryAccountBalanceResponse, error) {
	client := proto.NewAccountClient(m.cli.Conn())
	return client.QueryAccountBalance(ctx, in, opts...)
}

func (m *defaultAccount) DeductBalance(ctx context.Context, in *DeductBalanceRequest, opts ...grpc.CallOption) (*DeductBalanceResponse, error) {
	client := proto.NewAccountClient(m.cli.Conn())
	return client.DeductBalance(ctx, in, opts...)
}

func (m *defaultAccount) AddBalance(ctx context.Context, in *AddBalanceRequest, opts ...grpc.CallOption) (*AddBalanceResponse, error) {
	client := proto.NewAccountClient(m.cli.Conn())
	return client.AddBalance(ctx, in, opts...)
}

func (m *defaultAccount) IsAccountExist(ctx context.Context, in *AccountInfoRequest, opts ...grpc.CallOption) (*IsAccountExistResponse, error) {
	client := proto.NewAccountClient(m.cli.Conn())
	return client.IsAccountExist(ctx, in, opts...)
}
