// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: riskcontrol.proto

package server

import (
	"context"

	"github.com/Drengin6306/ZeroBank/service/riskcontrol/rpc/internal/logic"
	"github.com/Drengin6306/ZeroBank/service/riskcontrol/rpc/internal/svc"
	"github.com/Drengin6306/ZeroBank/service/riskcontrol/rpc/proto"
)

type RiskControlServiceServer struct {
	svcCtx *svc.ServiceContext
	proto.UnimplementedRiskControlServiceServer
}

func NewRiskControlServiceServer(svcCtx *svc.ServiceContext) *RiskControlServiceServer {
	return &RiskControlServiceServer{
		svcCtx: svcCtx,
	}
}

// 检查交易风险
func (s *RiskControlServiceServer) CheckTransaction(ctx context.Context, in *proto.RiskCheckRequest) (*proto.RiskCheckResponse, error) {
	l := logic.NewCheckTransactionLogic(ctx, s.svcCtx)
	return l.CheckTransaction(in)
}
