// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: transaction.proto

package server

import (
	"context"

	"github.com/Drengin6306/ZeroBank/service/transaction/rpc/internal/logic"
	"github.com/Drengin6306/ZeroBank/service/transaction/rpc/internal/svc"
	"github.com/Drengin6306/ZeroBank/service/transaction/rpc/proto"
)

type TransactionServer struct {
	svcCtx *svc.ServiceContext
	proto.UnimplementedTransactionServer
}

func NewTransactionServer(svcCtx *svc.ServiceContext) *TransactionServer {
	return &TransactionServer{
		svcCtx: svcCtx,
	}
}

// 获取交易流水
func (s *TransactionServer) GetTransactions(ctx context.Context, in *proto.TransactionRequest) (*proto.TransactionResponse, error) {
	l := logic.NewGetTransactionsLogic(ctx, s.svcCtx)
	return l.GetTransactions(in)
}
