// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: account.proto

package server

import (
	"context"

	"github.com/Drengin6306/ZeroBank/service/account/rpc/internal/logic"
	"github.com/Drengin6306/ZeroBank/service/account/rpc/internal/svc"
	"github.com/Drengin6306/ZeroBank/service/account/rpc/proto"
)

type AccountServer struct {
	svcCtx *svc.ServiceContext
	proto.UnimplementedAccountServer
}

func NewAccountServer(svcCtx *svc.ServiceContext) *AccountServer {
	return &AccountServer{
		svcCtx: svcCtx,
	}
}

func (s *AccountServer) GetAccountInfo(ctx context.Context, in *proto.AccountInfoRequest) (*proto.AccountInfoResponse, error) {
	l := logic.NewGetAccountInfoLogic(ctx, s.svcCtx)
	return l.GetAccountInfo(in)
}

func (s *AccountServer) QueryAccountBalance(ctx context.Context, in *proto.QueryAccountBalanceRequest) (*proto.QueryAccountBalanceResponse, error) {
	l := logic.NewQueryAccountBalanceLogic(ctx, s.svcCtx)
	return l.QueryAccountBalance(in)
}

func (s *AccountServer) DeductBalance(ctx context.Context, in *proto.DeductBalanceRequest) (*proto.DeductBalanceResponse, error) {
	l := logic.NewDeductBalanceLogic(ctx, s.svcCtx)
	return l.DeductBalance(in)
}

func (s *AccountServer) AddBalance(ctx context.Context, in *proto.AddBalanceRequest) (*proto.AddBalanceResponse, error) {
	l := logic.NewAddBalanceLogic(ctx, s.svcCtx)
	return l.AddBalance(in)
}
